#matrix:
#  include:
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - pip install -r www/requirements.txt
  - pip install coveralls

script:
  - cd ${TRAVIS_BUILD_DIR}/www
  - coverage run -m pytest
  - coverage report

after_success:
  - coveralls

#    - language: node_js
#      node_js:
#        - '9'
#        - '10'
#        - '11'
#
#      before_install:
#        - cd ${TRAVIS_BUILD_DIR}/app
#        - npm install
#
#      cache:
#        yarn: true
#        directories:
#          - 'node_modules'
#
#      script:
#        - cd ${TRAVIS_BUILD_DIR}/app
#        - npm test

notifications:
    slack: cimvhr-saans:Sor7cjZ280ryRSYs2byWUYm6
