#! /bin/bash
set -ex
[ -d venv ] || virtualenv venv
source venv/bin/activate
pip install -r requirements.txt


export APP_SETTINGS="project.server.config.TestingConfig"
export SECRET_KEY="justatest"

sudo -u postgres createuser boyle || true
sudo -u postgres psql -c 'drop database flask_jwt_auth' || true
sudo -u postgres psql -c 'drop database flask_jwt_auth_test' || true
sudo -u postgres psql -c 'create database flask_jwt_auth'
sudo -u postgres psql -c 'create database flask_jwt_auth_test'

sed -i "s/\(.*\<postgres_local_base\) = .*/\1 = 'postgresql:\/\/\/'/" project/server/config.py
sed -i "s/postgres:@localhost//" project/tests/test__config.py


rm -rf migrations

python manage.py db init
python manage.py db migrate
python manage.py db upgrade

python manage.py test
#python manage.py cov

python manage.py drop_db

pip list --outdated

# pip install --upgrade
# pip freeze > requirements.txt
