#! /bin/bash
[ -d venv ] || python3 -m venv venv
source ./venv/bin/activate
set -ex
[ ! -f requirements.txt ] || pip install -r requirements.txt
pip check

source venv/bin/activate

pip list --outdated --format=columns
# if this is failing:
# TypeError: '>' not supported between instances of 'Version' and 'Version'
# try re-installing a local (venv) version of pip:
# $ source venv/bin/activate
# $ pip install --force pip==9.0.0
# $ pip install -U pip

exec python -m stress ${1:-run}
