export default {
  "1": { id: 1, name: "SA - Continuous COP (projects)" },
  "2": { id: 2, name: "SA - DCOP (projects)" },
  "3": { id: 3, name: "SA - Sway 1.0 (projects)" },
  "4": { id: 4, name: "Static Balance Training" },
  "5": { id: 5, name: "RopeBridge" },
  "6": { id: 6, name: "Breakout " },
  "7": { id: 7, name: "Park " },
  "8": { id: 8, name: "Maze Choice" },
  "9": { id: 9, name: "Train" },
  "10": { id: 10, name: "Train" },
  "11": { id: 11, name: "Tricky Road" },
  "12": { id: 12, name: "Endless Road" },
  "13": { id: 13, name: "Smooth Pursuit" },
  "14": { id: 14, name: "Smooth Pursuit Walking backwards" },
  "15": { id: 15, name: "Christmas 2014 - Projects" },
  "16": { id: 16, name: "Hit Circle No Fireworks" },
  "17": { id: 17, name: "CUGM - Physics box drop " },
  "18": { id: 18, name: "Ed App - Car" },
  "19": { id: 19, name: "Boat " },
  "20": { id: 20, name: "Ed App - Bus" },
  "21": { id: 21, name: "Endless Road" },
  "22": { id: 22, name: "Market (projects)" },
  "23": { id: 23, name: "Catch Frenzy" },
  "24": { id: 24, name: "Catch Frenzy" },
  "25": { id: 25, name: "Catch Frenzy" },
  "26": { id: 26, name: "Building Block Apps - Platform Perturbation" },
  "27": { id: 27, name: "Manual Control (projects) " },
  "28": { id: 28, name: "Baseball Soccer" },
  "29": { id: 29, name: "Road " },
  "30": { id: 30, name: "City Ride " },
  "31": { id: 31, name: "Christmas 2011" },
  "32": { id: 32, name: "Christmas 2012" },
  "33": { id: 33, name: "Building Block Apps - OKS ALL" },
  "34": { id: 34, name: "MPL" },
  "35": { id: 35, name: "Ed App - TargetHands (projects)" },
  "36": { id: 36, name: "Manual Control" },
  "37": { id: 37, name: "Christmas 2013" },
  "38": { id: 38, name: "Tricky Road" },
  "39": { id: 39, name: "Ottawa Platform Final" },
  "40": { id: 40, name: "SS - LOS Envelope" },
  "41": { id: 41, name: "Park - People Walking" },
  "42": { id: 42, name: "3MDR" },
  "43": { id: 43, name: "Building Block Apps - VOR" },
  "44": { id: 44, name: "Ed App - Piano (projects)" },
  "45": { id: 45, name: "Tracking" },
  "46": { id: 46, name: "SS - Mediolateral Weight Graphics" },
  "47": { id: 47, name: "SS - Postural Stability" },
  "48": { id: 48, name: "SS - Visual Tracking" },
  "49": { id: 49, name: "Maze Choice" },
  "50": { id: 50, name: "Catch Frenzy " },
  "51": { id: 51, name: "Tricky Road" },
  "52": { id: 52, name: "Hit Circle " },
  "53": { id: 53, name: "Manual Control" },
  "54": { id: 54, name: "Tricky Road" },
  "55": { id: 55, name: "Christmas 2014" }
};
