export const SESSION_NOT_STARTED = "SESSION_NOT_STARTED";
export const ACTIVITY_ONGOING = "ACTIVITY_ONGOING";
export const RESTING = "RESTING";

// Deprecated
export const ACTIVITY_NOT_STARTED = "ACTIVITY_NOT_STARTED";
export const ACTIVITY_COMPLETED = "ACTIVITY_COMPLETED";
